### ISSUE TITLE
User can view navigation links.

### ISSUE THREAD

**Issue by vincelavang** [vincelavang/sway-finance#3]
#Motivation
Adding a navigation bar for easier page browsing.

#Task

- [x] Add FAQ text with link

- [x] Add Security text with link

- [x] Reposition and resize
